<a href="https://colab.research.google.com/github/ishantk/GW2022PD1/blob/master/GW2022PD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let us learn Machine Learning

In [ ]:
a = 10
b = 20
c = a+b
c

30

Problems in Machine Learning
1. Regression
2. Classification

Observation
1. 700, 800, 1
2. 1200, 1000, 1
3. 150, 100, 2
4. 300, 350, 2

In [1]:
from sklearn import tree
# Input
X = [[700, 800], [1200, 1000], [150, 100], [300, 350]]
# Output
Y = [1, 1, 2, 2]

model = tree.DecisionTreeClassifier()
model.fit(X, Y)

result = model.predict([[250, 180]])
print(result)
print(type(result))

[2]
<class 'numpy.ndarray'>


In [14]:
import numpy as np
np.__version__

'1.21.6'

In [15]:
numbers = [10, 20, 30, 40, 50]
print(numbers, type(numbers))

[10, 20, 30, 40, 50] <class 'list'>


In [16]:
array = np.array(numbers)
print(array, type(array))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [20]:
array = np.arange(10)
print(array)
print(array.shape)

image = [ [120, 22, 66], [22, 12, 88], [67, 12, 56] ]
array2d = np.array(image)
print(array2d)
print(array2d.shape)

# Explore Slicing on 1d and 2d array :)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[120  22  66]
 [ 22  12  88]
 [ 67  12  56]]
(3, 3)


In [32]:
numbers = [1, 1, 1, 1, 1, 1, 1, 1]
numbers = [0, 0, 0, 0, 0, 0, 0, 0]
print(numbers, len(numbers))

# array1 = np.ones(8)
# array1 = np.ones(8, dtype=np.int32)
array1 = np.zeros(8, dtype=np.int32)
print(array1)

print(array1.ndim)
print(array1.shape)

array2 = array1.reshape(2, 2, 2)
print(array2)
print(array2.ndim)
print(array2.shape)

array3 = array2.ravel()
print(array3)

[0, 0, 0, 0, 0, 0, 0, 0] 8
[0 0 0 0 0 0 0 0]
1
(8,)
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
3
(2, 2, 2)
[0 0 0 0 0 0 0 0]


In [36]:
chessboard = np.zeros((8, 8), dtype=np.int32)
print(chessboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [38]:
chessboard[1::2, 0::2] = 1
chessboard[0::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
